### ISSUE TITLE
RTOS Bring-up

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DataAcquisition2.0#134]
/**Description**
Figure out the development environment and dependency requirements for using RTOS. Get an LED blinky running

**Sub-tasks**
- [x] Explore vanilla FreeRTOS vs CMSIS-RTOS v1 vs CMSIS-RTOS v2. Select one in consideration of libraries and goals for the dual-core DAQ.
- [x] LED Blinky
- [x] Build a development environment for the repo
- [x] Document and test reproducibility

Tutorials
- [Digikey's FreeRTOS Getting Started tutorial](https://www.youtube.com/watch?v=OPrcpbKNSjU&list=PLEBQazB0HUyRYuzfi4clXsKUSgorErmBv&index=11&t=353s)
- [CMSIS-RTOS v2 API Docs](https://www.keil.com/pack/doc/CMSIS/RTOS2/html/rtos_api2.html)
- [Vanilla FreeRTOS features](https://www.freertos.org/Inter-Task-Communication.html)
- [Intro to FreeRTOS Ecosystem](https://www.einfochips.com/blog/freertos-insights-and-understanding-the-ecosystem/)
- [FreeRTOS+CLI library](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_CLI/FreeRTOS_Plus_Command_Line_Interface.html)
- [FreeRTOS+FAT library](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/index.html)

Youtube Playlists
- [ST's CMSIS-RTOS](https://www.youtube.com/playlist?list=PLnMKNibPkDnExrAsDpjjF1PsvtoAIBquX)
- [ControllersTech CMSIS-RTOS](https://www.youtube.com/playlist?list=PLfIJKC1ud8gj1t2y36sabPT4YcKzmN_5D)
- [Vanilla FreeRTOS](https://www.youtube.com/playlist?list=PLxGj5QMILu9GIB2PIgY_8RoRpRPOLvQ3J)

Reentrancy and newlib
- [Reentrancy and newlib](https://www.codeinsideout.com/blog/freertos/reentrant/#debug_1)
- [Steps to use FreeRTOS with newlib reentrant Memory Allocation](https://mcuoneclipse.com/2020/11/15/steps-to-use-freertos-with-newlib-reentrant-memory-allocation/)

Official Docs
- ["The Book" & Reference Manual](https://www.freertos.org/Documentation/RTOS_book.html)
