### ISSUE TITLE
Minimum Viable Product (MVP) w/ Previous Implementation

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DataAcquisition2.0#16]
**Description**
I have implemented my previous work in a [separate repo](https://github.com/DallasFormulaRacing/SDCard-Interface-STM32). Having moved from ST's HAL library to Mbed, figure out where to place the files to amongst our codebase, and make use of it for a basic implementation. This will be our fallback while guaranteeing this critical feature for the team. For convenience, determine whether the card insertion is consistent with the reset button.

**Sub-tasks**
- [ ] Move `init()` & `deinit()` autogenerated code to the Mbed environment
- [ ] Add the necessary files driver & BSP files for enabling FatFS
- [ ] Write a sample CSV file

**Definition of Done**
* Tested
* Code reviewed

**Comment by crsz20** [comment]
Different versions of the FatFS library & middleware resulted in a hard fault segmentation error. Examining assembly or bytes would have been necessary to trace down the error — this is not feasible nor desirable considering time restraints & long-term plans.
