### ISSUE TITLE
Get valid data from the sensor

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DataAcquisition2.0#2]
**Description**

**Sub-tasks**
- [x] Fix the temperature transfer function — there should be less drift
- [x] Modify the pressure output transfer function
- [x] Verify bit-shifting

**Definition of Done**
* Tested for stakeholder satisfaction
* Code Reviewed
