### ISSUE TITLE
Basic CSV File Writing Implementation

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DataAcquisition2.0#49]
**Description**
Instead of the .txt file created in Mbed's example for logging to an SD card, create & write to an SD-Card. You may need to get in touch with our Software Lead for ensuring the order of the data in which it needs to be parsed, the current standard, & any modifications we should make.

**Sub-tasks**
- [ ] Meet with our stakeholder, the software lead
- [ ] CSV header and dummy values are written
- [ ] Select an `error` value for failing hardware

Note: In the long term, once we have a better understanding of our hardware, we may like to create a separate text file for logging error messages. For now, an `error` value in the corresponding field will suffice.

**Definition of Done**
* Tested
* Code reviewed
