### ISSUE TITLE
Custom build system

### ISSUE THREAD

**Issue by crsz20** [DallasFormulaRacing/DataAcquisition2.0#94]
**Description**
Use CMake to build & compile the codebase. Find tools to then flash the dev board with our program.

**Sub-tasks**
- [ ] Compile a basic program
- [ ] Use the wildcard to compile includes/dependencies recursively
- [ ] Consider finding a 3rd party package manager ([CPM](https://medium.com/swlh/cpm-an-awesome-dependency-manager-for-c-with-cmake-3c53f4376766)?)

**Definition of Done**
* Tested
* Code reviewed
* Document all discovered approaches
